_BASE_: "Base-FCPose.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    NUM_CLASSES: 1
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
  # WARMUP_FACTOR: 1.0 / 3000
  # WARMUP_ITERS: 3000