_BASE_: "Base-FCPose.yaml"
SOLVER:
  STEPS: (180000, 240000)
  MAX_ITER: 270000
MODEL:
  FCOS:
    NUM_CLASSES: 1
  # FCPOSE:
  #   LOSS_WEIGHT_DIRECTION: 0.0
  #   LOSS_WEIGHT_KEYPOINT: 0.0
  #   BASIS_MODULE:
  #     LOSS_WEIGHT: 0.0