_BASE_: "../Base-BoxTeacher.yaml"
MODEL:
  WEIGHTS: "../../pretrained_models/swin_base_patch4_window7_224_ts.pth"
  BACKBONE:
    NAME: "build_retinanet_swin_transformer_fpn_backbone"
  SWIN_TRANSFORMER:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
INPUT:
  AUG_TYPE: "strongv2"
  AUG_EXTRA: True
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 16
  OPTIMIZER: "ADAMW"
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
OUTPUT_DIR: "output/boxteacher_swin_base_aug_3x"